baseURL = 'http://rctcwyvrn.github.io/optimization_portfolio'
languageCode = 'en-us'
title = 'Math 441 portfolio'
theme = "paper"
[params]
  # color style
  color = 'linen'                 # linen, wheat, gray, light